logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = "enable-debugging spoof-app-version vanced-microg-support wide-searchbar"
included-patches = ""                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "auto"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"


[YouTube Music]
build-mode = "both"
excluded-patches = "vanced-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm64-v8a"                                                     # both arm64-v8a and arm-v7a

[Twitter]
build-mode = "apk"
version = "auto"
included-patches = "dynamic-color hide-ads hide-recommended-users"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitter-inc/twitter/"

[Twitch]
build-mode = "apk"
included-patches = "auto-claim-channel points block-audio-ads block-embedded-ads block-video-ads settings show-deleted-messages"
excluded-patches = "debug-mode"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
